### ISSUE TITLE
How to run pre-trained model on custom data?

### ISSUE THREAD

**Issue by fomalhaut-b** [3dlg-hcvc/plan2scene#23]
I need to run the pre-trained models on some custom data I have. How do I do that? Do I just replace the data in appropriate folders of Rent3D++ data set? Reading the README, I could not understand how to use this repo out of the box to generate 3d plans for custom data. Awesome work btw:)

For example: 
Suppose I already have vectorised floor plan data along with photos mapped to some subset of rooms, and now want to use plan2scene using a pre-trained model for now, how can I do that?

**Comment by madhawav** [comment]
Hi, you have to convert the floorplan vector to the scene.json format we use. It should be straightforward conversion. Ill upload a doc explaining this format shortly. You can refer to the  Rent3D++ for example scene.json files.

**Comment by madhawav** [comment]
Hi @fomalhaut-b 
- The data organization of the Rent3D++ dataset is [explained here](https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/rent3dpp_data_organization.md). This document also explains the photoroom.csv files that we use to indicate the assignment of photos to rooms.
- The scene.json format we use to specify house architecture is [explained here](https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/scene_json_format.md).
- An example scene.json file is [provided here](https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/sample_scene_json.md).

Also, you have to do some additional optional steps explained in the readme, such as extracting rectified surface crops from photos. Refer to point 1.iii [here](https://github.com/3dlg-hcvc/plan2scene#data). 

Let me know if you need anything else.

**Comment by fomalhaut-b** [comment]
Hi @madhawav Thanks for the response. I understood that I have to convert to the scene.json file format. 

Now, the scene.json file contains several things as you have mentioned - wall, holes, materials, textures. etc. But everything won't be known beforehand right, most of this information will be filled by the algorithm. So, do I just put the things I know, and let other thing (like texture) to be filled by the algorithm?

**Comment by fomalhaut-b** [comment]
So, the way I understand it is. 
Use (http://art-programmer.github.io/floorplan-transformation/paper.pdf) for raster-vector transformation. This will give us the wall position, wall holes, etc. But it wont give texture and materials. These things will be given by plan2scene.

**Comment by fomalhaut-b** [comment]
Lastly, what are "CAD Objects" Didn't quite understand their role after reading your paper? Do we have to specify them as input? Or will it be in ouput? 

**I think adding a simple guide for custom inputs in the README would be great. I can help out it editing/making it. Thanks**

**Comment by madhawav** [comment]
Hi @fomalhaut-b 
1) You are correct. The plan2scene code will fill in the textures. So, you don't have to specify them in the scene.json files used as the input. Strictly speaking, what's necessary for texturing stages of Plan2Scene is the 'rooms' section (we identify room type from it) and the 'rdr' section (we generate the GNN graph representation using it) of scene.json files. Also, the photoroom.csv files are necessary. The rectified crops extracted from those photos are necessary. 

2) Your understanding is correct. Texturing is the core of what we do. But, we do provide a couple of additional scripts useful for CAD model placement given the object icon AABBs and door/window line segments from the floorplan vector (see details below).

3) 
**What are CAD objects?**
Raster-to-vector will provide you the object icons as axis-aligned bounding boxes (AABBs). It will provide doors/windows as line segments. To bring those into 3D, one has to place 3D shapes in place of those bounding boxes/line segments. It is those 3D shapes we call CAD models. 
We developed a simple set of rules to identify suitable 3D CAD models, and their placements (position, rotation, and scale), given the door/window line segments and object icon AABBs provided by a vectorization approach. This set of rules is described in the supplemental materials. 

**Should you provide CAD objects in the input?**
This is not required. As I mentioned above, we have devised a set of rules to identify CAD model placements. Applying these rules is optional and the instructions on how to apply these rules are [described by the scripts here](https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/place_cad_models.md). These scripts require object icon AABBs specified as ['objectabb.json' files](https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/rent3dpp_data_organization.md). Also, the doors/windows have to be specified as holes in the input scene.json. The output of those scripts will be scene.json files with the objects section populated.

**Does our output scene.json files have CAD objects?**
If you use the optional scripts above, then yes. Otherwise, No. 

I agree that having a simple guide for custom inputs will be useful. Any help is much appreciated!

**Comment by madhawav** [comment]
Hi @fomalhaut-b 
I have this old project which can convert raster-to-vector outputs to the scene.json format we use. I am refactoring it these days, so it can be merged with the Plan2Scene code. I will let you know when its merged.

**Comment by madhawav** [comment]
Hi @fomalhaut-b 
Here are the instructions on how to use raster-to-vector outputs with plan2scene: https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/plan2scene_on_r2v.md

Please let me know if you come across any issues.

**Comment by fomalhaut-b** [comment]
@madhawav thanks for the updates. These are very useful. I kind of dropped off this work since the exact use case wasn't matching, but I am planning to try to get it running in few months. Looks very interesting. The colab is very helpful btw!
